# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[[constraint]]
  name="github.com/miekg/dns"
  version="=v1.0.15"

[[constraint]]
  name="github.com/emicklei/go-restful"
  version="=v1.1.3"

[[constraint]]
  name="github.com/mesos/mesos-go"
  revision="068d5470506e3780189fe607af40892814197c5e"

[[constraint]]
  name="github.com/dgrijalva/jwt-go"
  version="=v2.7.0"
